### ISSUE TITLE
Unable to build Project

### ISSUE THREAD

**Issue by sumitsj16** [CoRE-RG/SignalsAndGateways#7]
I am working on OMNEST-6.0.3

And am getting the following errors.

ld.lld: warning: duplicate symbol: __NULL_IMPORT_DESCRIPTOR
>>> defined at libCoRE4INET_dbg.dll.a(libCoRE4INET_dbg.dll)
>>> defined at libINET_dbg.dll.a(libINET_dbg.dll)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: C:/OMNEST-6.0.3-eval/tools/win32.x86_64/mingw64/bin/ld.lld -m i386pep --shared -Bdynamic -e DllMainCRTStartup --enable-auto-image-base -o ../out/clang-debug/src/libSignalsAndGateways_dbg.dll C:/OMNEST-6.0.3-eval/tools/win32.x86_64/mingw64/lib/dllcrt2.o C:/OMNEST-6.0.3-eval/tools/win32.x86_64/mingw64/lib/gcc/x86_64-w64-mingw32/12.1.0/crtbegin.o -L../../../CoRE4INET-master/CoRE4INET-master/src -L../../../FiCo4OMNeT-master/FiCo4OMNeT-master/src -L../../../inet-3.8.5-src/inet/src -LC:/OMNEST-6.0.3-eval/tools/win32.x86_64/usr/bin -LC:/OMNEST-6.0.3-eval/tools/win32.x86_64/opt/mingw64/lib -LC:/OMNEST-6.0.3-eval/lib -LC:/OMNEST-6.0.3-eval/tools/win32.x86_64/mingw64/lib/gcc/x86_64-w64-mingw32/12.1.0 -LC:/OMNEST-6.0.3-eval/tools/win32.x86_64/mingw64/x86_64-w64-mingw32/lib -LC:/OMNEST-6.0.3-eval/tools/win32.x86_64/mingw64/lib -LC:/OMNEST-6.0.3-eval/tools/win32.x86_64/mingw64/x86_64-w64-mingw32/sys-root/mingw/lib ../out/clang-debug/src/signalsandgateways/applications/can/CanSinkGatewayApp.o ../out/clang-debug/src/signalsandgateways/applications/can/CanSourceGatewayApp.o ../out/clang-debug/src/signalsandgateways/applications/ethernet/EthernetGatewayApplication.o ../out/clang-debug/src/signalsandgateways/gateway/buffering/AccumulationGatewayBuffering.o ../out/clang-debug/src/signalsandgateways/gateway/buffering/NoGatewayBuffering.o ../out/clang-debug/src/signalsandgateways/gateway/messages/GatewayAggregationMessage.o ../out/clang-debug/src/signalsandgateways/gateway/routing/BaseGatewayRouter.o ../out/clang-debug/src/signalsandgateways/gateway/transformation/GatewayTransformation.o ../out/clang-debug/src/signalsandgateways/gateway/transformation/NoGatewayTransformation.o ../out/clang-debug/src/signalsandgateways/gateway/messages/GatewayAggregationMessage_m.o ../out/clang-debug/src/signalsandgateways/gateway/messages/PoolMessage_m.o ../out/clang-debug/src/signalsandgateways/gateway/messages/UnitMessage_m.o --allow-multiple-definition --whole-archive -lCoRE4INET_dbg -lFiCo4OMNeT_dbg -lINET_dbg --no-whole-archive -loppenvir_dbg -loppsim_dbg -lstdc++ --out-implib ../out/clang-debug/src/libSignalsAndGateways_dbg.dll.a --output-def ../out/clang-debug/src/libSignalsAndGateways_dbg.def -lstdc++ -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -lkernel32 C:/OMNEST-6.0.3-eval/tools/win32.x86_64/mingw64/lib/gcc/x86_64-w64-mingw32/12.1.0/crtend.o

 #0 0x00007ff6b877db39 (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x17db39)
 #1 0x00007ff6b878247a (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x18247a)
 #2 0x00007ff6b8658db3 (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x58db3)
 #3 0x00007ff6b8660bed (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x60bed)
 #4 0x00007ff6b876ffee (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x16ffee)
 #5 0x00007ff6b8776c11 (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x176c11)
 #6 0x00007ff6b87925a0 (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x1925a0)
 #7 0x00007ff6b881f2ad (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x21f2ad)
 #8 0x00007ff6b863e11d (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x3e11d)
 #9 0x00007ff6b894e3d6 (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x34e3d6)
#10 0x00007ff6b86013ae (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x13ae)
#11 0x00007ff6b86014e6 (C:\OMNEST-6.0.3-eval\tools\win32.x86_64\mingw64\bin\ld.lld.exe+0x14e6)
#12 0x00007ffdecc8259d (C:\Windows\System32\KERNEL32.DLL+0x1259d)
#13 0x00007ffdecf8af38 (C:\Windows\SYSTEM32\ntdll.dll+0x5af38)

clang++: error: linker command failed due to signal (use -v to see invocation)
make[1]: *** [Makefile:135: ../out/clang-debug/src/libSignalsAndGateways_dbg.dll] Error 1
make[1]: Leaving directory '/c/OMNEST-6.0.3-eval/samples/SignalsAndGateways-master/SignalsAndGateways-master/src'
make: *** [Makefile:34: all] Error 2
"make MODE=debug -j8 all" terminated with exit code 2. Build might be incomplete.

Kindly help understand the issue and the fix
